### ISSUE TITLE
New log's owner is root instead of netadmin

### ISSUE THREAD

**Issue by viktorcsimma** [EotvosCollegium/mars#310]
Every UTC midnight (that means 2 AM now), new log files are created under `/var/www/mars/storage/logs/`; but they are owned by `root`, not by `netadmin` with whose permissions Apache runs. Because of this, every time something has to be logged (e. g. when saving the application form), a 500 response is sent.

For now, I've created a cron job `30 * * * * chown netadmin:netadmin -R /var/www/mars/` with `sudo crontab -u root -e` which should set back the permissions every hour at minute 30. But maybe there is a better solution for this.

**Comment by kdmnk** [comment]
Hm. Good catch. It should be the new wifi related job that is run by root instead of laravel. Not sure why.

________________________________
From: Viktor Csimma ***@***.***>
Sent: Thursday, July 27, 2023 8:00:00 PM
To: EotvosCollegium/mars ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EotvosCollegium/mars] New log's owner is root instead of netadmin (Issue #310)


Every UTC midnight (that means 2 AM now), new log files are created under /var/www/mars/storage/logs/; but they are owned by root, not by netadmin with whose permissions Apache runs. Because of this, every time something has to be logged (e. g. when saving the application form), a 500 response is sent.

For now, I've created a cron job 1 0 * * * chown netadmin:netadmin /var/www/mars/storage/logs/* with sudo crontab -u root -e which should set back the permissions every day at 00:01 UTC (I haven't seen yet whether it works; I'll check it out tomorrow), but maybe there is a better solution for this.

**Comment by horcsinbalint** [comment]
If the log was not created by the `netadmin` user before, `root` would create it, therefore `root:root` would be the owner of the file. I think it is an operational problem and not a problem with mars, therefore I would recommend closing this issue.

**Comment by viktorcsimma** [comment]
Yes; I remember seeing something in root's cronjobs that did something with the logs. But after the reinstall, it's not actual anyway.

**Comment by horcsinbalint** [comment]
I am closing this issue as it is user error
