### ISSUE TITLE
Add new anonymous questions to the evaluation form

### ISSUE THREAD

**Issue by viktorcsimma** [EotvosCollegium/mars#530]
We've got a request to add some [new questions](https://docs.google.com/forms/d/1VxKF_DznSfeyq9TND2q8QhOMt8IqLxzGn7B8MDMZh6M/edit). These, however, should be anonymous and we should only store the _year of admission_ and the _status_ (resident or extern) with the answers.

The easiest solution would be to use the same mechanism as for the feedback question now (i.e. sending an email). A bit more advanced way is to add a single table (let's say, `anonymous_answers`), with a column for the year, the status and each question. A more difficult, but also more flexible approach would be to also create a table for the questions themselves, which could be editable without changing the code.

@kdmnk what do you think?

**Comment by kdmnk** [comment]
I don't support this as it is now.

Again, I feel like these questions can be relevant now, but might not in long term (at least they will want us to change the questions)

We need some ensurance that this worth the development and maintenance effort. Otherwise, I don't see any benefit from integrating this with the system.

As a workaround, we can add external links, or start implementing a survey system with user defined questions, but it only worths it if we get a relatively huge benefit by connecting it to statuses/semesters/users*/etc.

*we have mr/miss integrated because before that, summarizing the results took multiple hours




________________________________
From: Viktor Csimma ***@***.***>
Sent: Wednesday, May 15, 2024 8:03:23 PM
To: EotvosCollegium/mars ***@***.***>
Cc: Katkó Dominik ***@***.***>; Mention ***@***.***>
Subject: [EotvosCollegium/mars] Add new anonymous questions to the evaluation form (Issue #530)


We've got a request to add some new questions<https://docs.google.com/forms/d/1VxKF_DznSfeyq9TND2q8QhOMt8IqLxzGn7B8MDMZh6M/edit>. These, however, should be anonymous and we should only store the year of admission and the status (resident or extern) with the answers.

The easiest solution would be to add a single table (let's say, anonymous_answers), with a column for the year, the status and each question. A more difficult, but also more flexible approach would be to also create a table for the questions themselves, which could be editable without changing the code.

@kdmnk<https://github.com/kdmnk> what do you think?

**Comment by viktorcsimma** [comment]
Now that you're saying; you are right... I think the reason might be that this way, we essentially force them to fill these questions (as a Google Form would probably be ignored by a large proportion). But I'll ask them.

**Comment by viktorcsimma** [comment]
Yepp; the main idea is that they would not fill it otherwise. And I cannot think of a more effective way right now...

**Comment by kdmnk** [comment]
Yeah, I get that but still. We can add an external link for a better reach. 
Or if you want to implement it, at least make the questions editable, that can be useful.

**Comment by kdmnk** [comment]
What about the following?

Generalise the questions from the general assemblies such that:
- add option to answer as text
- remove isOpened and isClosed, use general assemblies open and closed date instead - if that's realistic (or make them nullable)
- use [polymorphic relation](https://laravel.com/docs/11.x/eloquent-relationships#one-to-many-polymorphic-relations) to use the questions both for general assemblies and for semester evaluation
- add a section for the semester evaluation where the questions are edited by the student council and can be filled only once. Remove the previous anonymus feedback question.

**Comment by viktorcsimma** [comment]
Mhm... and then we could use the existing infrastructure; that's a good idea. The isOpened/isClosed date should remain; it is usually used at the assembly.

**Comment by horcsinbalint** [comment]
As it should be anonymous and I don't think anybody would want to submit an answer more than once (it is not something like an election), we can just simply embed a form from Google Forms using an iframe. It can be changed at each semester by a 
We can do something like this:
![image](https://github.com/EotvosCollegium/mars/assets/51171286/6bdf4c2d-b4ce-433e-9acf-54977060ee51)

**Comment by kdmnk** [comment]
That's a good idea :) If we have that we can remove the general feedback part cause it's a bit silly with the email sending
